### ISSUE TITLE
Some days have been skipped

### ISSUE THREAD

**Issue by sanchobarriga** [froi/tracking-puertorico-covid19#34]
**Describe the bug**
Upon verification, various days have been skipped. It is unclear what the cause of this may have been. 

**To Reproduce**
1. Go to 'https://tracking-covid-pr.froi.dev/'
2. Scroll down to any variable still in use, such as 'Censo de Pacientes Pediátricos en Intensivo Sin Covid'
3. Note discontinuities in data collection. 

**Expected behavior**

Daily data was published for dates missing, but seem to have not been obtained by the automated extraction design. 

**Desktop (please complete the following information):**
 - OS: Windows 10. 
 - Browser: Chrome

**Additional context**
Note, this issue may not be possible to fix retroactively, as there is no clear repository of historical data, however, identifying why certain dates may have been skipped could facilitate this not occurring again.

**Comment by froi** [comment]
Thanks for making this issue. I'll take a look at it.

Sadly there is no way to retroactively obtain data that was skipped. The data that is being consumed is a bit unreliable as it is not meant to be consumed the way it is. That said there are a number of fixes needed.

There are also time that the data that is returned is `null` for whatever reason that does not make sense to me.

**Comment by sanchobarriga** [comment]
Hi, Froi,

I don't know if you had the time to take a look at it, but it seems that July 2nd, was the last day the data was appropriately collected.

**Comment by froi** [comment]
Sorry for the radio silence on this. As most can imagine this is no longer being maintained. I'm going to be exporting the data that was collected and putting this repo in archive mode.
